import type { DocCategory } from '../types'

export const MOCK_CATEGORIES: DocCategory[] = [
  {
    id: 'getting-started',
    code: '01',
    title: 'Быстрый старт',
    icon: '🚀',
    description: 'Основная информация о платформе LERN и начале обучения',
    progressPercent: 100,
    items: [
      {
        id: 'welcome',
        categoryId: 'getting-started',
        code: '01.1',
        title: 'Добро пожаловать в LERN',
        description: 'Вводная статья о возможностях интерактивной учебной платформы',
        status: 'completed',
        author: {
          name: 'Алексей Смирнов',
          avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
          role: 'Lead Architect',
        },
        updatedAt: '2026-08-30',
        readTimeMinutes: 3,
        tags: ['Обзор', 'Старт', 'LERN'],
        usefulCount: 42,
        notUsefulCount: 1,
        flashcard: {
          id: 'fc-01-1',
          category: 'LERN Codex',
          section: 'Введение',
          difficulty: 'easy',
          question: 'В чём главная идея концепции Bookish Codex в LERN?',
          answer: 'Слияние академического книжного справочника с 3D-тренажерами памяти Active Recall для глубокого и долгосрочного запоминания.',
          hint: 'Подумайте об эстетике книги и технике интервального повторения.',
        },
        quiz: {
          question: 'Какой ключевой инструмент используется в LERN для борьбы с забыванием материала?',
          correctId: 'b',
          explanation: '3D-карточки Active Recall заставляют мозг активно извлекать информацию из памяти, что укрепляет синаптические связи.',
          options: [
            { id: 'a', label: 'A', text: 'Пассивное перечитывание конспекта' },
            { id: 'b', label: 'B', text: '3D-карточки интервального повторения Active Recall' },
            { id: 'c', label: 'C', text: 'Просмотр длинных видеолекций на фоне' },
          ],
        },
        sections: [
          {
            id: 'about-platform',
            title: 'Что такое LERN?',
            level: 2,
            text: 'LERN — это современная микрофронтенд-платформа интерактивного обучения с подсистемами тренажеров, личным кабинетом ученика и преподавательской аналитикой.',
            callout: {
              type: 'tip',
              message: 'Рекомендуется изучить раздел Архитектуры перед началом разработки своих модулей.',
            },
          },
          {
            id: 'key-features',
            title: 'Ключевые возможности',
            level: 2,
            text: 'Платформа предоставляет готовые виджеты для отображения курсов, прохождения интерактивных тестов и проверки кода в реальном времени.',
          },
          {
            id: 'quick-example',
            title: 'Пример структуры модуля',
            level: 3,
            text: 'Вот как выглядит базовый шаблон интеграции с экосистемой LERN:',
            codeSnippet: {
              language: 'typescript',
              filename: 'src/app/init.ts',
              code: `import { createLernApp } from '@lern/core'

export const app = createLernApp({
  theme: 'codex-navy',
  features: ['analytics', 'interactive-labs']
})`,
            },
          },
        ],
      },
      {
        id: 'navigation-guide',
        categoryId: 'getting-started',
        code: '01.2',
        title: 'Навигация по платформе',
        description: 'Как быстро переключаться между кабинетом, тренажерами и курсами',
        status: 'completed',
        author: {
          name: 'Елена Васильева',
          avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
          role: 'UX Designer',
        },
        updatedAt: '2026-08-28',
        readTimeMinutes: 4,
        tags: ['UX', 'Навигация'],
        usefulCount: 29,
        notUsefulCount: 0,
        flashcard: {
          id: 'fc-01-2',
          category: 'Навигация',
          section: 'Интерфейс',
          difficulty: 'easy',
          question: 'Как осуществляется переключение между микрофронтендами платформы?',
          answer: 'Через глобальный хост-маршрутизатор (Host Shell Router) и механизм Webpack Module Federation без полной перезагрузки страницы.',
        },
        quiz: {
          question: 'Какая технология обеспечивает независимую загрузку микрофронтендов?',
          correctId: 'c',
          options: [
            { id: 'a', label: 'A', text: 'iFrame вставки' },
            { id: 'b', label: 'B', text: 'Серверный рендеринг через Nginx rewrite' },
            { id: 'c', label: 'C', text: 'Webpack Module Federation' },
          ],
        },
        sections: [
          {
            id: 'top-nav',
            title: 'Верхняя панель навигации',
            level: 2,
            text: 'В шапке всегда доступны ключевые переходы: главная страница, документация, личный кабинет ученика и переключатель цветового оформления тем.',
          },
        ],
      },
    ],
  },
  {
    id: 'architecture',
    code: '02',
    title: 'Архитектура и FSD',
    icon: '⚖️',
    description: 'Стандарты Feature-Sliced Design, структура модулей и интеграция сервисов',
    progressPercent: 50,
    items: [
      {
        id: 'fsd-standards',
        categoryId: 'architecture',
        code: '02.1',
        title: 'Стандарты Feature-Sliced Design',
        description: 'Правила разделения приложения на слои: app, pages, widgets, features, entities, shared',
        status: 'in-progress',
        author: {
          name: 'Алексей Смирнов',
          avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
          role: 'Lead Architect',
        },
        updatedAt: '2026-09-02',
        readTimeMinutes: 6,
        tags: ['FSD', 'Архитектура', 'TypeScript'],
        usefulCount: 54,
        notUsefulCount: 2,
        flashcard: {
          id: 'fc-02-1',
          category: 'FSD',
          section: 'Архитектура',
          difficulty: 'medium',
          question: 'Разрешен ли импорт из вышележащих слоев в нижележащие по стандарту FSD?',
          answer: 'Категорически запрещен. Слой Shared не может импортировать ничего выше себя, Entities знают только о Shared, а Features — о Entities и Shared.',
          hint: 'Вспомните золотое правило направленности зависимостей FSD.',
        },
        quiz: {
          question: 'Какой слой в FSD инкапсулирует бизнес-сущность предметной области (данные и тип)?',
          correctId: 'b',
          options: [
            { id: 'a', label: 'A', text: 'features' },
            { id: 'b', label: 'B', text: 'entities' },
            { id: 'c', label: 'C', text: 'widgets' },
          ],
        },
        sections: [
          {
            id: 'layers-hierarchy',
            title: 'Иерархия слоёв FSD',
            level: 2,
            text: 'В проекте строго соблюдается изоляция слоев. Запрещены циклические импорты и импорты сверху вниз.',
            callout: {
              type: 'warning',
              message: 'Компоненты слоя Shared никогда не должны импортировать файлы из Entities или Features.',
            },
          },
          {
            id: 'public-api',
            title: 'Публичный API через index.ts',
            level: 3,
            text: 'Каждый модуль экспортирует свои наружные интерфейсы и компоненты исключительно через корневой index.ts (barrel export).',
            codeSnippet: {
              language: 'typescript',
              filename: 'src/entities/user/index.ts',
              code: `export * from './model/types'
export * from './api/user-api'
export { default as UserAvatar } from './ui/user-avatar/user-avatar.vue'`,
            },
          },
        ],
      },
      {
        id: 'services-and-adapters',
        categoryId: 'architecture',
        code: '02.2',
        title: 'Слои сервисов и адаптеров',
        description: 'Преобразование API DTO в UI Model и работа со стейтом',
        status: 'locked',
        author: {
          name: 'Алексей Смирнов',
          avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
          role: 'Lead Architect',
        },
        updatedAt: '2026-09-01',
        readTimeMinutes: 5,
        tags: ['Services', 'Adapters'],
        usefulCount: 18,
        notUsefulCount: 0,
        flashcard: {
          id: 'fc-02-2',
          category: 'Архитектура',
          section: 'Адаптеры',
          difficulty: 'hard',
          question: 'Для чего в архитектуре используется слой адаптеров (Adapters)?',
          answer: 'Адаптеры преобразуют внешние сырые структуры сервера (DTO) во внутренние модели пользовательского интерфейса (UI Models), защищая UI от изменений в API.',
        },
        quiz: {
          question: 'Где должен располагаться адаптер данных сущности?',
          correctId: 'a',
          options: [
            { id: 'a', label: 'A', text: 'Внутри модуля сущности в папке adapters/' },
            { id: 'b', label: 'B', text: 'Внутри Vue-компонента в теге <template>' },
            { id: 'c', label: 'C', text: 'В глобальном router/index.ts' },
          ],
        },
        sections: [
          {
            id: 'adapter-pattern',
            title: 'Паттерн Адаптер',
            level: 2,
            text: 'Адаптеры гарантируют, что изменение формата ответа бэкенда не сломает весь интерфейс приложения.',
          },
        ],
      },
    ],
  },
  {
    id: 'active-recall',
    code: '03',
    title: 'Реактивность и Обучение',
    icon: '🧠',
    description: 'Методика Active Recall, Composition API и интервальное повторение',
    progressPercent: 0,
    items: [
      {
        id: 'spaced-repetition',
        categoryId: 'active-recall',
        code: '03.1',
        title: 'Механика интервального повторения',
        description: 'Алгоритм SuperMemo-2 и расчет оптимальных интервалов для карточек',
        status: 'locked',
        author: {
          name: 'Елена Васильева',
          avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
          role: 'UX Designer',
        },
        updatedAt: '2026-08-25',
        readTimeMinutes: 4,
        tags: ['Active Recall', 'Память', 'Алгоритмы'],
        usefulCount: 31,
        notUsefulCount: 1,
        flashcard: {
          id: 'fc-03-1',
          category: 'Психология памяти',
          section: 'Интервалы',
          difficulty: 'medium',
          question: 'Что описывает кривая забывания Эббингауза?',
          answer: 'Экспоненциальное угасание памяти во времени, если материал не повторяется через увеличивающиеся промежутки времени.',
        },
        quiz: {
          question: 'Когда наиболее эффективно производить первое повторение нового материала?',
          correctId: 'b',
          options: [
            { id: 'a', label: 'A', text: 'Через месяц' },
            { id: 'b', label: 'B', text: 'Через 24 часа после первичного изучения' },
            { id: 'c', label: 'C', text: 'Никогда, если хорошо понял сразу' },
          ],
        },
        sections: [
          {
            id: 'ebbinghaus-curve',
            title: 'Кривая Эббингауза',
            level: 2,
            text: 'Без интервального повторения через 72 часа в памяти сохраняется менее 20% изученного материала.',
          },
        ],
      },
    ],
  },
]

export const MOCK_COURSES: import('../types').CourseCodex[] = [
  {
    id: 'course-lern-core',
    slug: 'lern-architecture',
    title: 'Архитектура LERN & Bookish Codex',
    description: 'Полное академическое руководство по платформе LERN: микрофронтенды, FSD, Vue 3, 3D-тренажеры Active Recall и создание курсов.',
    category: 'Архитектура & Frontend',
    icon: '🎓',
    level: 'intermediate',
    author: {
      id: 'author-1',
      name: 'Алексей Смирнов',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
      role: 'Lead Architect',
    },
    tags: ['Vue 3', 'TypeScript', 'FSD', 'Module Federation', 'Active Recall'],
    isPublished: true,
    totalChapters: 6,
    estimatedHours: 4,
    createdAt: '2026-08-15',
    updatedAt: '2026-09-01',
    modules: MOCK_CATEGORIES,
  },
  {
    id: 'course-vue3-mastery',
    slug: 'vue3-mastery',
    title: 'Мастерство Vue 3: Composition API & Pinia',
    description: 'Глубокое погружение в реактивность Vue 3, effectScope, кастомные composables и масштабируемые хранилища Pinia.',
    category: 'Frontend',
    icon: '⚡',
    level: 'advanced',
    author: {
      id: 'author-2',
      name: 'Николай Разработчик',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
      role: 'Senior Frontend Engineer',
    },
    tags: ['Vue 3', 'Composition API', 'Pinia', 'Reactivity', 'TypeScript'],
    isPublished: true,
    totalChapters: 3,
    estimatedHours: 6,
    createdAt: '2026-09-10',
    updatedAt: '2026-10-02',
    modules: [
      {
        id: 'vue3-reactivity',
        code: '01',
        title: 'Реактивное ядро Vue 3',
        icon: '🔬',
        description: 'Принципы работы Proxy, Track & Trigger и управление жизненным циклом реактивности',
        progressPercent: 0,
        items: [
          {
            id: 'vue3-ref-reactive',
            categoryId: 'vue3-reactivity',
            code: '01.1',
            title: 'Ref против Reactive: ментальные модели',
            description: 'Различия между упаковкой примитивов в RefImpl и проксированием объектов',
            status: 'in-progress',
            author: {
              name: 'Николай Разработчик',
              avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
              role: 'Senior Frontend Engineer',
            },
            updatedAt: '2026-10-01',
            readTimeMinutes: 5,
            tags: ['Vue 3', 'Reactivity', 'Ref'],
            usefulCount: 28,
            notUsefulCount: 0,
            flashcard: {
              id: 'fc-vue-1',
              category: 'Vue 3 Core',
              section: 'Реактивность',
              difficulty: 'medium',
              question: 'Почему деструктуризация reactive() теряет реактивность, а toRefs() сохраняет её?',
              answer: 'Деструктуризация копирует свойства по значению из JavaScript Proxy. toRefs оборачивает каждое свойство в Ref, связанный с исходным прокси через геттеры и сеттеры.',
              hint: 'Вспомните, как работают обычные объекты JS при деструктуризации.',
            },
            quiz: {
              question: 'Что возвращает функция ref(10)?',
              correctId: 'b',
              explanation: 'Ref оборачивает значение в объект RefImpl со свойством .value.',
              options: [
                { id: 'a', label: 'A', text: 'Proxy-объект' },
                { id: 'b', label: 'B', text: 'Объект с реактивным геттером/сеттером .value' },
                { id: 'c', label: 'C', text: 'Обычное примитивное число' },
              ],
            },
            sections: [
              {
                id: 'sec-ref-intro',
                title: 'Основа реактивности: Proxy и RefImpl',
                level: 2,
                text: 'Vue 3 перешёл от Object.defineProperty к ES6 Proxy. Это позволило перехватывать добавление и удаление свойств, а также прозрачно работать с массивами и коллекциями Map/Set.',
                callout: {
                  type: 'tip',
                  message: 'В TypeScript проектах рекомендуется использовать ref() везде, так как он сохраняет единообразие доступа через .value.',
                },
              },
              {
                id: 'sec-ref-code',
                title: 'Пример правильного использования toRefs',
                level: 3,
                text: 'Используйте toRefs при передаче полей состояния в шаблон:',
                codeSnippet: {
                  language: 'typescript',
                  filename: 'use-counter.ts',
                  code: 'import { reactive, toRefs } from \'vue\'\n\nexport function useCounter() {\n  const state = reactive({ count: 0, multiplier: 2 })\n  return { ...toRefs(state) }\n}',
                },
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'course-postgres-db',
    slug: 'postgres-db',
    title: 'PostgreSQL: от реляционной модели до индексов',
    description: 'Проектирование надежных реляционных схем, ACID-транзакции, B-Tree и GIN индексы и профилирование EXPLAIN ANALYZE.',
    category: 'Backend & Базы данных',
    icon: '🗄️',
    level: 'intermediate',
    author: {
      id: 'author-3',
      name: 'Михаил Архитектор',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
      role: 'Database Architect',
    },
    tags: ['PostgreSQL', 'SQL', 'Databases', 'Performance', 'Backend'],
    isPublished: true,
    totalChapters: 2,
    estimatedHours: 5,
    createdAt: '2026-09-20',
    updatedAt: '2026-10-04',
    modules: [
      {
        id: 'pg-indexes',
        code: '01',
        title: 'Индексы и производительность',
        icon: '⚡',
        description: 'Внутреннее устройство B-Tree индексов, планировщик запросов и сканирование',
        progressPercent: 0,
        items: [
          {
            id: 'pg-btree-deep',
            categoryId: 'pg-indexes',
            code: '01.1',
            title: 'Как устроен B-Tree индекс в PostgreSQL',
            description: 'Структура сбалансированного дерева, поиск O(log N) и когда индекс не используется',
            status: 'in-progress',
            author: {
              name: 'Михаил Архитектор',
              avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
              role: 'Database Architect',
            },
            updatedAt: '2026-10-04',
            readTimeMinutes: 6,
            tags: ['PostgreSQL', 'Indexes', 'B-Tree'],
            usefulCount: 45,
            notUsefulCount: 1,
            flashcard: {
              id: 'fc-pg-1',
              category: 'PostgreSQL Core',
              section: 'Индексы',
              difficulty: 'hard',
              question: 'Почему планировщик PostgreSQL может выбрать Seq Scan вместо Index Scan даже при наличии индекса?',
              answer: 'Если по статистике планировщика запрос затрагивает большую долю строк таблицы (например, >15-20%), последовательное чтение блоков диска дешевле случайных чтений страниц индекса и кучи.',
              hint: 'Подумайте о стоимости случайного (random) и последовательного (sequential) I/O диска.',
            },
            quiz: {
              question: 'Какой тип индекса по умолчанию создаётся командой CREATE INDEX?',
              correctId: 'a',
              explanation: 'По умолчанию в PostgreSQL всегда создаётся B-Tree индекс.',
              options: [
                { id: 'a', label: 'A', text: 'B-Tree' },
                { id: 'b', label: 'B', text: 'Hash' },
                { id: 'c', label: 'C', text: 'GIN' },
              ],
            },
            sections: [
              {
                id: 'sec-pg-intro',
                title: 'B-Tree: Сбалансированное дерево страниц',
                level: 2,
                text: 'Индексы B-Tree состоят из корневой страницы, промежуточных страниц и листовых страниц. Листовые страницы содержат отсортированные ключи и указатели (TID) на физические строки в таблице.',
                callout: {
                  type: 'info',
                  message: 'Всегда проверяйте планы выполнения с помощью команды EXPLAIN (ANALYZE, BUFFERS).',
                },
              },
            ],
          },
        ],
      },
    ],
  },
]

